server:
  http_listen_port: 9080
  grpc_listen_port: 9095

clients:
  - url: http://loki:3100/loki/api/v1/push  # Адрес Loki для отправки логов

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'docker'  # Логирование с меткой job="docker"
          __path__: /var/lib/docker/containers/*/*.log  # Путь к логам Docker
