server:
  http_listen_port: 9080
  grpc_listen_port: 9095

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^/]*/)?[^/]+)
          source: tag
      - regex:
          expression: (?P<image_name>[^:]+)(?::[^:]+)?
          source: tag
      - labels:
          stream:
          container_name:
          image_name:
      - output:
          source: output