server:
  http_listen_port: 9080
  grpc_listen_port: 9095

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'docker'
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
      - labels:
          level:
          message:

  - job_name: 'nodejs-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'nodejs-app'
          __path__: /var/log/nodejs/*.log