{
 "title": "app от винстона",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"nodejs-app\"}[1m])) by (level)"
    }
   ]
  },
  {
   "title": "Error Count (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"nodejs-app\", level=\"error\"}[24h]))"
    }
   ]
  },
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nodejs-app\"} | json"
    }
   ]
  }
 ]
}